In [2]:
import numpy as np
import torch

In [4]:
# View (원소의 수를 유지하면서 텐서의 크기 변경)
# view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야함 ex) (2, 2, 3)=2*2*3=12 -> (4, 3)=4*3=12
# 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추함

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape)

torch.Size([2, 2, 3])


In [5]:
# 3차원 텐서에서 2차원 텐서로 변경
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [6]:
# 3차원 텐서의 크기 변경 (2 × 2 × 3) = (? × 1 × 3) = 12 => ? = 4
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [11]:
# 스퀴즈(Squeeze) : 1인 차원을 제거
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().dim())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
1
torch.Size([3])


In [17]:
# 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가
ft = torch.Tensor([0, 1, 2])

print(ft.shape)
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미, 첫번째 차원에 1 추가 (3,) -> (1,3)
print(ft.unsqueeze(0).shape)
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

print(ft.unsqueeze(1)) # 두번째 차원에 1 추가 (3,) -> (3,1)
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1)) # -1은 인덱스 상으로 마지막 차원을 의미 (현재 크기가 (3,)이었으므로 마지막 차원에 1인 차원을 추가하면 (3, 1))
print(ft.unsqueeze(-1).shape)


# view(), squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [21]:
# Type Casting

# Long 타입 -> float
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

# Byte 타입 -> long, float
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [25]:
# concatenate - 두 텐서를 연결
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0)) # 첫번째 차원(행)을 늘리라는 의미
print(torch.cat([x, y], dim=1)) # 두번째 차원(열)을 늘리라는 의미

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [28]:
# Stacking - 연결(concatenate)을 하는 또 다른 방법
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z])) # 아래와 동일한 연산, 더 간단히 가능!
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # (2,) -> (1,2) -> (3,2)
print(torch.stack([x, y, z], dim=1)) # 두번째 차원이 증가하도록 쌓으라는 의미

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [30]:
# ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(x)
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [33]:
# In-place Operation (연산 뒤에 _를 붙이면 기존의 값을 덮어씀)
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력 (연산 뒤에 _ => 기존 값 덮어씀)
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
